SELECT (count(blattnummer)=0)
FROM alb_baulastblatt_baulasten
JOIN alb_baulastblatt ON (alb_baulastblatt.baulasten=alb_baulastblatt_baulasten.baulastblatt_reference)
WHERE alb_baulastblatt_baulasten.baulast IN
    (SELECT alb_baulast.id
     FROM alb_baulast
     LEFT OUTER JOIN alb_baulast_flurstuecke_belastet ON (alb_baulast.flurstuecke_belastet=alb_baulast_flurstuecke_belastet.baulast_reference)
     GROUP BY alb_baulast.id HAVING count(alb_baulast_flurstuecke_belastet.baulast_reference) = 0);
